guest=['xin','liu','wu']
print(guest[0]+',Please come for dinner!')
print(guest[1]+',Please come for dinner!')
print(guest[2]+',Please come for dinner!')
gue=guest.pop()
print(gue+' cannot come.')
guest.append('li')
print(guest)
print(guest[0]+',Please come for dinner!')
print(guest[1]+',Please come for dinner!')
print(guest[2]+',Please come for dinner!')
print("I got a larger table!")
guest.insert(0,'jiang')
guest.insert(2,'zhang')
guest.append('nie')
print(guest)
print("I'm sorry for that the larger table is delayed!")
print(guest.pop()+",I'm sorry for that i cannot ivite you to dinner!")
print(guest.pop()+",I'm sorry for that i cannot ivite you to dinner!")
print(guest.pop()+",I'm sorry for that i cannot ivite you to dinner!")
print(guest.pop()+",I'm sorry for that i cannot ivite you to dinner!")
print(guest[0]+" you're invited to dinner!!")
print(guest[1]+" you're invited to dinner!!")
del guest[1]
del guest[0]
print(guest)
